### ISSUE TITLE
HDF4 installation

### ISSUE THREAD

**Issue by piyushether** [HDFGroup/hdf4#1]
Hi, 

I was installing the hdf4 library in my new system and I encountered the following error while "make >& gmake.out" and the same for gmake check >& check.out".
error in gmake.out:

`libtool: compile:  /usr/bin/gfortran -O -c mfgrff.f -o mfgrff.o`
`mfgrff.f:155:48:`
` `
  `132 |       mgsnatt = mgisattr(riid, name, nt, count, data, len(name))`
`      |                                                2`
`......`
`  155 |       mgsattr = mgisattr(riid, name, nt, count, data, len(name))`
`      |                                                1`
`Error: Type mismatch between actual argument at (1) and actual argument at (2) (CHARACTER(0)/INTEGER(4)).`
`gmake[3]: *** [Makefile:679: mfgrff.lo] Error 1`
`gmake[3]: Leaving directory '/home/piyush/myHdfNcStuff/hdf4-master/hdf/src'`
`gmake[2]: *** [Makefile:485: all] Error 2`
`gmake[2]: Leaving directory '/home/piyush/myHdfNcStuff/hdf4-master/hdf/src'`
`gmake[1]: *** [Makefile:425: all-recursive] Error 1`
`gmake[1]: Leaving directory '/home/piyush/myHdfNcStuff/hdf4-master/hdf'`
`gmake: *** [Makefile:515: all-recursive] Error 1`

**Comment by byrnHDF** [comment]
Added warning flag to treat this as no-error. Will be in next release, currently in development branch.

**Comment by byrnHDF** [comment]
In addition, fortran is disabled by default because of it's dependence on 32-bit pointer assumptions.

**Comment by byrnHDF** [comment]
New release and disable-fortran by default addresses this issue
