### ISSUE TITLE
Disable Fortran on 64-bit builds

### ISSUE THREAD

**Issue by derobins** [HDFGroup/hdf4#103]
The ancient Fortran 77 interface assigns pointers to fortran INTEGER values (usually 32-bit), which is not portable to systems where pointers are 64 bits.

CMake/configure should determine the size of pointers and FORTRAN integers and prevent building the Fortran interface when they are incompatible. Alternatively, the Fortran interface could be retired or updated to a newer version of Fortran that allows 64-bit integers.

From dff.c:

```
/*-----------------------------------------------------------------------------  
 * Name:    dfiopen                                                              
 * Purpose: call DFopen to open HDF file                                         
 * Inputs:  name: name of file to open                                           
 *      acc_mode: access mode - integer with value DFACC_READ etc.               
 *      defdds: default number of DDs per header block                           
 *      namelen: length of name                                                  
 * Returns: 0 on success, -1 on failure with DFerror set                         
 * Users:   HDF Fortran programmers                                              
 * Invokes: DFopen                                                               
 * Method:  Convert filename to C string, call DFopen                            
 * Note: DFopen actually return *DF.  In machines that a pointer                 
 *       is bigger than a Fortran INTEGER, this routine would fail.              
 *       This is a design error and has no easy portable solution.               
 *---------------------------------------------------------------------------*/ 
```

**Comment by sumseq** [comment]
Does this mean HDF4 can no longer work with Fortran?  There are a lot of Fortran users of HDF4 out there (including myself).
Is there a fix being worked on for this?
What "bad" thing can happen if the Fortran library is built?
We have been using hdf4 1.12 with Fortran on modern systems and it seems fine.
Is this a newer problem?

**Comment by derobins** [comment]
Closing this. There's a discussion and fixing Fortran is on the 4.4.0 roadmap.
