### ISSUE TITLE
hdf/test/comp.c msan failure on write

### ISSUE THREAD

**Issue by schwehr** [HDFGroup/hdf4#143]
With master's current head with a custom linux build...

My guess is that `init_buffers(void)` is not fully initializing all the buffers

```
InitTest("comp", test_comp, "COMPRESSED ELEMENTS"); 
```

Fails here:

```
  if (HI_WRITE(file_rec->file, buf, bytes) == FAIL)
```

Fails with:

```
Testing  -- COMPRESSED ELEMENTS (comp) 
Uninitialized bytes in __interceptor_fwrite at offset 513 inside [0x72000000e000, 514)
==5664==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fa69ea9df0b in HP_write third_party/hdf4/hdf/src/hfile.c:3593:9

SUMMARY: MemorySanitizer: use-of-uninitialized-value third_party/hdf4/hdf/src/hfile.c:3593:9 in HP_write
Exiting
```

**Comment by derobins** [comment]
What are your sanitizer settings? I'm not seeing this on Linux or MacOS with either clang or gcc.

I've been fixing a bunch of memory issues over the past few days. Most of them are due to type mismatches that cause buffers to overrun.

**Comment by schwehr** [comment]
I'm pretty sure this particular one is fixed.  Not sure which commit did it, but I can no longer reproduce.  Closing.
