### ISSUE TITLE
XDR Undefined References

### ISSUE THREAD

**Issue by eddsalkield** [HDFGroup/hdf4#15]
Hi there,

I'm attempting to build a package for Alpine Linux from v4.2.15.  However, when trying to link in the XDR types, `ld` is failing with many undefined references, for example to `xdr_u_long`.

I initially suspected that this was the incompatibility mentioned in section 4.4 of [this document](https://github.com/HDFGroup/hdf4/blob/master/release_notes/INSTALL), meaning my system's version of xdr (portablexdr) is incompatible with this project.

Therefore I supplied configure with `--enable-hdf4-xdr`, and removed portablexdr from my system.  The bundled version of XDR gets compiled, but I get the same behaviour.

The full linker output can be found [here](https://gist.github.com/eddsalkield/f870d601dfb27052d2c94f8156d1de54).  I'd appreciate any input you can give as to how I might proceed :)

**Comment by eddsalkield** [comment]
I've managed to get the software to build - I needed to instruct the linker to link to `libportablexdr`.  After installing `libportablexdr-dev`, I ran `export LIBS="-lportablexdr"` before `./configure --prefix=/usr`.

Would you consider adding this linker flag to the makefile in case somebody else wants to use `libportablexdr-dev` as well?

**Comment by derobins** [comment]
I'm hoping to remove XDR entirely and then this problem would go away. If I can't by the next release I'll try to add XDR lib and include paths like we do libjpeg.

**Comment by derobins** [comment]
This will be "fixed" when we remove XDR in 4.3.0 :)
