### ISSUE TITLE
error: conflicting types for ‘xdrposix_inline’

### ISSUE THREAD

**Issue by davesworking** [HDFGroup/hdf4#26]
I am trying to build on Linux-ARM64 platform. Getting an error:

hdf4/mfhdf/libsrc/xdrposix.c:530:1: error: conflicting types for ‘xdrposix_inline’

Is there a change required to hdfi.h or xdrposix.c to build on Linux-ARM64? (x86 platforms are not an issue)

Thanks!

**Comment by hyoklee** [comment]
@davesworking , I could build one for Linux-ARM64 using CMake:

https://github.com/hyoklee/hdf4/actions/workflows/aarch64.yml

Click the Workflow file to see how it was built and test passed.

**Comment by davesworking** [comment]
we managed to get it build with some changes to xdrposic.c and hdfi.h
thanks!
