### ISSUE TITLE
(HDFFR-1593) Crash in VSinquire on a customer file

### ISSUE THREAD

**Issue by bmribler** [HDFGroup/hdf4#303]
Date: Tue, 31 Aug 2021 14:42:20 +0000
From:
To: "prioritysupport@hdfgroup.org" <prioritysupport@hdfgroup.org>
Subject: Crash in VSinquire on a customer file
Parts/Attachments:
"(customer file).hdf"
"repro.cpp"
----------------------------------------

Hi HDF Priority Support!

We have a customer-reported crash on their HDF4 file (see (customer file).hdf attached), and I was able to
reproduce it outside (company name/product). Attached is the C repro code, repro.cpp, and the customer file, (customer file).hdf
(the customer said the file should only be shared for necessary debugging/investigation). When I run the repro code,
I see the following output (this was ran on a mac, but we see this crash on other platforms too):

file_id after Hopen: 536870912
status after Vstart: 0
count after Vlone (1): 3
count after Vlone (2): 3
refs[0]: 46
refs[1]: 47
refs[2]: 1427
vgroup_id after Vattach: 805306374
nChild after Vntagrefs: 6
nChild after Vgettagrefs: 6
vdata_id after VSattach: 1073741824
Bus error: 10

The crash seems to happen during VSinquire call. This is the relevant portion of the (company name/product) crash stack trace, in
case it is helpful:

[ 7] 0x00000000610f51c3 [unknown function] at [unknown module] (no module specified)
[ 8] 0x0000000197942d71 scanattrs+00000236
[ 9] 0x000000019793aa05 VSsizeof+00000288
[ 10] 0x000000019793b365 VSinquire+00000176

Note that we are using the 4.2.5 HDF4 version.

Is this a (known) bug? Is there some corruption in the customer file? We would appreciate any information about this
issue.

Thank you very much!

JIRA issue: https://jira.hdfgroup.org/browse/HDFFR-1593

**Comment by derobins** [comment]
Fixed in 4.2.16
