### ISSUE TITLE
(HDFFR-1573) SDwritedata fails after calling SDgetchunkinfo

### ISSUE THREAD

**Issue by bmribler** [HDFGroup/hdf4#308]
SDwritedata fails after calling SDgetchunkinfo

Version: hdf-4.2.14

We have existing code developed with HDF4.2r1 that is failing with the latest hdf versions.

Attached sample program demonstrates the problem. Build commands used are in the comments.
----
*Reported through helpdesk: SUPPORT-251*

From blj: I created a C version, myhdftest.c, just in case I was not seeing something in the C++ code.
It also shows the issue with SDwritedata failing. 
Comment out the call to SDgetchunkinfo and then the code works properly.

JIRA issue: https://jira.hdfgroup.org/browse/HDFFR-1573

**Comment by derobins** [comment]
Fixed in 4.2.16
