### ISSUE TITLE
HDF4 specification of Image dimensions

### ISSUE THREAD

**Issue by JohnLCaron** [HDFGroup/hdf4#359]
https://support.hdfgroup.org/release4/doc/DS.pdf

1)
p 9-125

DFTAG_LUT 
Lookup table
xdim * ydim * elements * NTsize bytes (xdim, ydim, elements,
and NTsize are specified in the corresponding DFTAG_ID)
301 (0x012D)

Should probably say "... are specified in the corresponding DFTAG_LD". It would make no sense to have the lookup table be the same dimensions as the image.

I have at least one example file that has an LUT without LD, so all I can do is ignore. There is also an IP8 tag so I can use that.

2)
p 9-124

DFTAG_RI
Raster image
xdim * ydim * elements * NTsize bytes (xdim, ydim, elements, 
and NTsize are specified in the corresponding DFTAG_ID)
302 (0x012E)

This one is more speculative on my part, but it doesnt make sense for elements to be anything other than 1, so one could just leave that out.

**Comment by hyoklee** [comment]
@bmribler Please don't forget to convert FrameMaker documents to MS Word documents.

**Comment by bmribler** [comment]
@JohnLCaron
1. You are correct, DFTAG_ID should be DFTAG_LD for LUT, I'll make this correction.
2.  My understanding is "elements" is 1 for B/W (gray scale) but for color images, it can be a different number, such as 3 for RGB color scheme.

**Comment by bmribler** [comment]
Please add new comments to https://github.com/HDFGroup/hdf4doc/issues/8
