### ISSUE TITLE
Possible to get h4fc through CMake?

### ISSUE THREAD

**Issue by mathomp4** [HDFGroup/hdf4#4]
I've been trying to build HDF4 using CMake and I got close, but when I built it, I didn't get out `h4fc`. I did compile for Fortran and I see `libmfhdf_fortran.a` in my install dir, but no `h4fc`. If I look around I see code for `h4cc`:

https://github.com/HDFGroup/hdf4/blob/f6903b6ad6643a79d29c1cd53fac9dc4d6820031/mfhdf/libsrc/CMakeLists.txt#L172-L185

but I see no references to `h4fc` in the CMake files. Help?

**Comment by byrnHDF** [comment]
That had not been added yet. We have it in the works and will add it to the repo this month.

**Comment by mathomp4** [comment]
> That had not been added yet. We have it in the works and will add it to the repo this month.

Thanks. I also just found that [`h5pfc` isn't possible with HDF5 `develop`](https://forum.hdfgroup.org/t/can-h4fc-and-h5pfc-be-built-with-cmake/8825/2?u=matthew.thompson). Should I file an issue at https://github.com/HDFGroup/hdf5 ? Or is this already known?

**Comment by byrnHDF** [comment]
Will be in next release, currently in development branch.

**Comment by byrnHDF** [comment]
hdf5 issue already known and addressed.
