### ISSUE TITLE
`_FillValue` is not a valid C symbol

### ISSUE THREAD

**Issue by schwehr** [HDFGroup/hdf4#419]
In newer compilers, `_FillValue` is triggering issues.

See also: https://github.com/Unidata/netcdf-c/issues/2728

Use a most recent version of GCC or CLANG and enforce standards compliance:

- https://devblogs.microsoft.com/oldnewthing/20230109-00/?p=107685
- https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html

https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf

>  All identifiers that begin with an underscore and either an uppercase letter or another
underscore are always reserved for any use.

https://github.com/HDFGroup/hdf4/blob/df73ad82ac29c85f86a48ad9ce851a052b9a1ecf/hdf/src/hlimits.h#L275

```
/* For SD interface  */
#define _FillValue "_FillValue"
```

```
In file included from third_party/gdal/frmts/hdf4/hdf4multidim.cpp:28:
In file included from third_party/gdal/frmts/hdf4/hdf4dataset.h:37:
In file included from third_party/gdal/gcore/gdal_pam.h:35:
In file included from third_party/gdal/gcore/gdal_priv.h:77:
In file included from third_party/stl/cxx17/vector:30:
In file included from include/c++/v1/vector:316:
include/c++/v1/__bit_reference:268:16: error: expected ',' or '>' in template-parameter-list
  268 | template <bool _FillValue, class _Cp>
      |                ^
third_party/hdf4/hdf/src/hlimits.h:275:20: note: expanded from macro '_FillValue'
  275 | #define _FillValue "_FillValue"
      |                    ^
In file included from third_party/gdal/frmts/hdf4/hdf4multidim.cpp:28:
In file included from third_party/gdal/frmts/hdf4/hdf4dataset.h:37:
In file included from third_party/gdal/gcore/gdal_pam.h:35:
In file included from third_party/gdal/gcore/gdal_priv.h:77:
In file included from third_party/stl/cxx17/vector:30:
In file included from include/c++/v1/vector:316:
include/c++/v1/__bit_reference:268:26: error: expected unqualified-id
  268 | template <bool _FillValue, class _Cp>
      |                          ^
/include/c++/v1/__bit_reference:1102:18: error: expected ',' or '>' in template-parameter-list
 1102 |   template <bool _FillValue, class _Dp>
      |                  ^
third_party/hdf4/hdf/src/hlimits.h:275:20: note: expanded from macro '_FillValue'
  275 | #define _FillValue "_FillValue"
      |                    ^
```

**Comment by derobins** [comment]
I'd be thrilled to fix this (as we did with the include guards in HDF5), but there are a LOT of symbols that start with underscores in HDF4. hlimits.h is part of the public API so I doubt we can change it without driving people nuts.

**Comment by schwehr** [comment]
I think this change would be safe as long as people aren't overriding the behavior of the hdf4 headers. But I recognize the project isn't ready for this type of fix. Closing.
