### ISSUE TITLE
possible cleanup: Remove comment at the end of function closing braces

### ISSUE THREAD

**Issue by schwehr** [HDFGroup/hdf4#449]
If folks are okay with this idea, I can make a PR. I'm trying to find non-controversial things that tighten up the code without risk of breaking anything.

Consider:

```c
int32
HCPcskphuff_stread(accrec_t *access_rec)
{
    int32 ret;

    if ((ret = HCIcskphuff_staccess(access_rec, DFACC_READ)) == FAIL)
        HRETURN_ERROR(DFE_CINIT, FAIL);
    return ret;
} /* HCPcskphuff_stread() */    // <---- This comment here
```

Some functions have a closing function name comment and others do not. With modern editors, there shouldn't need to be these comments as there is brace matching and code folding/hiding. The code base is currently a mix of with and without these comments. If it feels like a function really needs one, I'd hazard a guess that it's a strong signal that the function is to large and should be broken up.

I propose removing all of these end of function comments.

Currently:

```shell
cd hdf/src

egrep '^}$' *.c | wc -l
449

egrep '^}.+' *.c | wc -l
839
```

**Comment by bmribler** [comment]
The problem is hdf4 has many very large functions.  We made attempts to shorten them over the years but not many are done yet.   We can remove the end function comments when more of the large functions disappear.  I'll concentrate on that in the next releases.

**Comment by schwehr** [comment]
> The problem is hdf4 has many very large functions

Sounds like a tooling issue with displaying code in whatever editors folks are using. The existing code is a mixture of style with and without these comments. And the comments frequently exist on functions that are super short.

I recognize that the project isn't ready for this kind of cleanup, so I'm closing the issue.

**Comment by bmribler** [comment]
> And the comments frequently exist on functions that are super short.

I know what you're saying.  Once, I started on a few long functions, I tried to stay consistent by applying the same style to all the functions I came across or added, but didn't go around and apply to all the functions in the library.  So much for staying consistent, but it was a WIP. :-/
