### ISSUE TITLE
cmake build does not install man pages

### ISSUE THREAD

**Issue by opoplawski** [HDFGroup/hdf4#474]
Is it possible to get it to do so?

**Comment by opoplawski** [comment]
Hmm, I guess they are already in the source - just not installed.

**Comment by byrnHDF** [comment]
I guess no one had complained about it before?
Speaking of documentation, we will be adding doxygen.

**Comment by derobins** [comment]
The man pages are incomplete. We've removed them for now while we investigate generating them from something like doxy2man.

**Comment by opoplawski** [comment]
I *really* wish they weren't removed.  I'm sure I'll get bug reports in Fedora about missing man pages.  Hopefully they will return shortly.
