### ISSUE TITLE
No rule to make target atom.c

### ISSUE THREAD

**Issue by waarmond** [HDFGroup/hdf4#694]
I've just tried to compile current git sources with gcc 13.2.1:
```
Making all in hdf
make[1]: Entering directory '/home/papa/aur/_kartographie_ml/hdf4/src/build/hdf'
Making all in src
make[2]: Entering directory '/home/papa/aur/_kartographie_ml/hdf4/src/build/hdf/src'
make  all-am
make[3]: Entering directory '/home/papa/aur/_kartographie_ml/hdf4/src/build/hdf/src'
make[3]: *** No rule to make target '/home/papa/aur/_kartographie_ml/orfeo62/hdf4/src/hdf-4.2.14/hdf/src/atom.c', needed by 'atom.lo'.  Stop.
```

Is this failure maybe a byproduct of the recent cleanup e.g. https://github.com/HDFGroup/hdf4/pull/677 ?

**Comment by derobins** [comment]
atom.c is definitely built. Our CI wouldn't pass without it and hdf/src/Makefile.am and hdf/src/CMakeLists.txt both include it.

If you are building from master with the Autotools, you'll need to run autogen.sh to build configure, Makefile.in, etc. We removed generated Autotools files from non-release branches in 4.2.16.
