### ISSUE TITLE
Incorrect version in configure.ac?

### ISSUE THREAD

**Issue by mathomp4** [HDFGroup/hdf4#786]
While trolling around the HDF4 repo files to see if Fortran support was back yet (at least on 64-bit systems[^1]), I noticed this in `configure.ac`:

https://github.com/HDFGroup/hdf4/blob/c57c571749c95b719aa76817319c6f4ae8d6bbcb/configure.ac#L27

Should that be changed to 4.3.0?

NOTE: I am not an Autotools guru (I can barely hack if needed), so maybe the actual version is some how parsed from a file. But I thought I'd bring it up.

[^1]: Doesn't look like it from my reading...but not sure.

**Comment by lrknox** [comment]
Thank you for reporting this.  For the master branch it should be changed to 4.3.1-1.  It should have been 4.3.0 in the 4.3.0 release. 

The actual version is specified in file hdf/src/hfile.h.  This incorrect version string in configure.ac is used only in the configure file and its output.

**Comment by mathomp4** [comment]
> Thank you for reporting this. For the master branch it should be changed to 4.3.1-1. It should have been 4.3.0 in the 4.3.0 release.
> 
> The actual version is specified in file hdf/src/hfile.h. This incorrect version string in configure.ac is used only in the configure file and its output.

@lrknox Ahh. okay I figured it was something like that as I noticed your `CMakeLists.txt` doesn't have a `VERSION` in it directly but was grepping some file (I guess that header). Autotools is...exciting to try and read. 😄
